config/routes.rb
Rails.application.routes.draw do
  
  root 'home#home'
  get '/movies', to: "home#movies"
  get '/reviews', to: 'home#reviews'
  get '/about', to: 'home#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def movies
  end

  def reviews
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Movie Review Site"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<% provide(:title, 'About') %>
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Movie Review App</h1>

  <h2>
    This is the home page for the movie review app for TCI.
  </h2>
  <%= react_component("Movies") %>
</div>

app/views/home/movies.html.erb
<% provide(:title, 'Movies') %>
<h1>Home#movies</h1>
<p>Find me in app/views/home/movies.html.erb</p>

app/views/home/reviews.html.erb
<% provide(:title, 'Reviews') %>
<h1>Home#reviews</h1>
<p>Find me in app/views/home/reviews.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Movie Reviews", root_url, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_url %></li>
            <li><%= link_to "Movies",   movies_path %></li>
            <li><%= link_to "Reviews", reviews_path %></li>
            <li><%= link_to "About", about_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>